// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Ad struct {
	AdID       string
	AdGroupID  string
	Type       string
	Content    string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
	IsApproval sql.NullBool
}

type AdGroup struct {
	AdGroupID  string
	CampaignID string
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
	IsApproval sql.NullBool
}

type Campaign struct {
	CampaignID string
	UserID     string
	Name       string
	Budget     int32
	StartDate  time.Time
	EndDate    time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
	IsApproval sql.NullBool
}

type Impression struct {
	ImpressionID string
	AdID         string
	Date         time.Time
	Impressions  int32
	Clicks       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Role struct {
	RoleID      string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Targeting struct {
	TargetingID string
	AdID        string
	Type        string
	Value       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type User struct {
	UserID         string
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type UserRole struct {
	UserID    string
	RoleID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
