// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createCampaign = `-- name: CreateCampaign :execresult
INSERT INTO campaigns (campaign_id, user_id, name, budget, start_date, end_date) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCampaignParams struct {
	CampaignID string
	UserID     string
	Name       string
	Budget     int32
	StartDate  time.Time
	EndDate    time.Time
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCampaign,
		arg.CampaignID,
		arg.UserID,
		arg.Name,
		arg.Budget,
		arg.StartDate,
		arg.EndDate,
	)
}

const createImpression = `-- name: CreateImpression :execresult
INSERT INTO impressions (impression_id, ad_id, date, impressions, clicks) VALUES (?, ?, ?, ?, ?)
`

type CreateImpressionParams struct {
	ImpressionID string
	AdID         string
	Date         time.Time
	Impressions  int32
	Clicks       int32
}

func (q *Queries) CreateImpression(ctx context.Context, arg CreateImpressionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createImpression,
		arg.ImpressionID,
		arg.AdID,
		arg.Date,
		arg.Impressions,
		arg.Clicks,
	)
}

const createTargeting = `-- name: CreateTargeting :execresult
INSERT INTO targeting (targeting_id, ad_id, type, value) VALUES (?, ?, ?, ?)
`

type CreateTargetingParams struct {
	TargetingID string
	AdID        string
	Type        string
	Value       string
}

func (q *Queries) CreateTargeting(ctx context.Context, arg CreateTargetingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTargeting,
		arg.TargetingID,
		arg.AdID,
		arg.Type,
		arg.Value,
	)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (user_id,role) VALUES (?,?)
`

type CreateUserParams struct {
	UserID string
	Role   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.UserID, arg.Role)
}

const deleteAd = `-- name: DeleteAd :execresult
UPDATE ads SET deleted_at = CURRENT_TIMESTAMP WHERE ad_id = ?
`

func (q *Queries) DeleteAd(ctx context.Context, adID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAd, adID)
}

const deleteCampaign = `-- name: DeleteCampaign :execresult
UPDATE campaigns SET deleted_at = CURRENT_TIMESTAMP WHERE campaign_id = ?
`

func (q *Queries) DeleteCampaign(ctx context.Context, campaignID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCampaign, campaignID)
}

const deleteImpression = `-- name: DeleteImpression :execresult
UPDATE impressions SET deleted_at = CURRENT_TIMESTAMP WHERE impression_id = ?
`

func (q *Queries) DeleteImpression(ctx context.Context, impressionID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteImpression, impressionID)
}

const deleteTargeting = `-- name: DeleteTargeting :execresult
UPDATE targeting SET deleted_at = CURRENT_TIMESTAMP WHERE targeting_id = ?
`

func (q *Queries) DeleteTargeting(ctx context.Context, targetingID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTargeting, targetingID)
}

const deleteUser = `-- name: DeleteUser :execresult
UPDATE users SET deleted_at = CURRENT_TIMESTAMP WHERE user_id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, userID)
}

const getCampaignById = `-- name: GetCampaignById :one
SELECT campaign_id, user_id, name, budget, start_date, end_date, created_at, updated_at, deleted_at, is_approval FROM campaigns WHERE campaign_id = ? LIMIT 1
`

func (q *Queries) GetCampaignById(ctx context.Context, campaignID string) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignById, campaignID)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.UserID,
		&i.Name,
		&i.Budget,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsApproval,
	)
	return i, err
}

const getCampaignsByUserId = `-- name: GetCampaignsByUserId :many
SELECT campaign_id, user_id, name, budget, start_date, end_date, created_at, updated_at, deleted_at, is_approval FROM campaigns WHERE user_id = ?
`

func (q *Queries) GetCampaignsByUserId(ctx context.Context, userID string) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, getCampaignsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.CampaignID,
			&i.UserID,
			&i.Name,
			&i.Budget,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImpressionById = `-- name: GetImpressionById :one
SELECT impression_id, ad_id, date, impressions, clicks, created_at, updated_at, deleted_at FROM impressions WHERE impression_id = ? LIMIT 1
`

func (q *Queries) GetImpressionById(ctx context.Context, impressionID string) (Impression, error) {
	row := q.db.QueryRowContext(ctx, getImpressionById, impressionID)
	var i Impression
	err := row.Scan(
		&i.ImpressionID,
		&i.AdID,
		&i.Date,
		&i.Impressions,
		&i.Clicks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getImpressionsByAdId = `-- name: GetImpressionsByAdId :many
SELECT impression_id, ad_id, date, impressions, clicks, created_at, updated_at, deleted_at FROM impressions WHERE ad_id = ?
`

func (q *Queries) GetImpressionsByAdId(ctx context.Context, adID string) ([]Impression, error) {
	rows, err := q.db.QueryContext(ctx, getImpressionsByAdId, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Impression
	for rows.Next() {
		var i Impression
		if err := rows.Scan(
			&i.ImpressionID,
			&i.AdID,
			&i.Date,
			&i.Impressions,
			&i.Clicks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTargetingByAdId = `-- name: GetTargetingByAdId :many
SELECT targeting_id, ad_id, type, value, created_at, updated_at, deleted_at FROM targeting WHERE ad_id = ?
`

func (q *Queries) GetTargetingByAdId(ctx context.Context, adID string) ([]Targeting, error) {
	rows, err := q.db.QueryContext(ctx, getTargetingByAdId, adID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Targeting
	for rows.Next() {
		var i Targeting
		if err := rows.Scan(
			&i.TargetingID,
			&i.AdID,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTargetingById = `-- name: GetTargetingById :one
SELECT targeting_id, ad_id, type, value, created_at, updated_at, deleted_at FROM targeting WHERE targeting_id = ? LIMIT 1
`

func (q *Queries) GetTargetingById(ctx context.Context, targetingID string) (Targeting, error) {
	row := q.db.QueryRowContext(ctx, getTargetingById, targetingID)
	var i Targeting
	err := row.Scan(
		&i.TargetingID,
		&i.AdID,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, role, created_at, updated_at, deleted_at FROM users WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCampaign = `-- name: UpdateCampaign :execresult
UPDATE campaigns SET name = ?, budget = ?, start_date = ?, end_date = ?, updated_at = CURRENT_TIMESTAMP WHERE campaign_id = ?
`

type UpdateCampaignParams struct {
	Name       string
	Budget     int32
	StartDate  time.Time
	EndDate    time.Time
	CampaignID string
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCampaign,
		arg.Name,
		arg.Budget,
		arg.StartDate,
		arg.EndDate,
		arg.CampaignID,
	)
}

const updateImpression = `-- name: UpdateImpression :execresult
UPDATE impressions SET impressions = ?, clicks = ?, updated_at = CURRENT_TIMESTAMP WHERE impression_id = ?
`

type UpdateImpressionParams struct {
	Impressions  int32
	Clicks       int32
	ImpressionID string
}

func (q *Queries) UpdateImpression(ctx context.Context, arg UpdateImpressionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateImpression, arg.Impressions, arg.Clicks, arg.ImpressionID)
}

const updateTargeting = `-- name: UpdateTargeting :execresult
UPDATE targeting SET type = ?, value = ?, updated_at = CURRENT_TIMESTAMP WHERE targeting_id = ?
`

type UpdateTargetingParams struct {
	Type        string
	Value       string
	TargetingID string
}

func (q *Queries) UpdateTargeting(ctx context.Context, arg UpdateTargetingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTargeting, arg.Type, arg.Value, arg.TargetingID)
}
